### PR TITLE
[port] permute to new api

### PR DESCRIPTION
**Pull request by kshitij12345**

### CODE REVIEW

**Comment by vfdev-5** [comment]
@kshitij12345 can you also try to use `REDUCTION_BOXED_ARGS` which can reduce the code duplication. See for example one of my previous PRs: https://github.com/facebookresearch/functorch/pull/138#issuecomment-926225956

**Comment by kshitij12345** [comment]
> @kshitij12345 can you also try to use REDUCTION_BOXED_ARGS which can reduce the code duplication. See for example one of my previous PRs: #138 (comment)

Do you mean for `cosine_similarity` #171?

**Comment by vfdev-5** [comment]
@kshitij12345 no, this one

**Comment by kshitij12345** [comment]
Tried but unfortunately it is not working

<details>

<summary>Patch</summary>

```patch
diff --git a/functorch/csrc/BatchRulesReduceOps.cpp b/functorch/csrc/BatchRulesReduceOps.cpp
index fe7c14a..fecf1d1 100644
--- a/functorch/csrc/BatchRulesReduceOps.cpp
+++ b/functorch/csrc/BatchRulesReduceOps.cpp
@@ -306,6 +306,7 @@ TORCH_LIBRARY_IMPL(aten, FT_BATCHED_KEY, m) {
   REDUCTION_BOXED(var_mean.correction);
   REDUCTION_BOXED(_log_softmax);
   REDUCTION_BOXED_ARGS(rot90, 2);
+  REDUCTION_BOXED(permute);
 
   VMAP_SUPPORT("_log_softmax_backward_data", _log_softmax_backward_batch_rule);
   VMAP_SUPPORT("_softmax_backward_data", _softmax_backward_batch_rule);
diff --git a/functorch/csrc/BatchRulesViews.cpp b/functorch/csrc/BatchRulesViews.cpp
index bd84883..9f6cad4 100644
--- a/functorch/csrc/BatchRulesViews.cpp
+++ b/functorch/csrc/BatchRulesViews.cpp
@@ -328,19 +328,19 @@ std::tuple<Tensor,optional<int64_t>> diagonal_backward_batch_rule(
   return std::make_tuple(std::move(result), 0);
 }
 
-std::tuple<Tensor, optional<int64_t>> permute_batching_rule(
-    const Tensor &self, optional<int64_t> self_bdim, IntArrayRef dims)
-{
-  TORCH_INTERNAL_ASSERT(self_bdim.has_value());
-  VmapDimVector dims_;
-  dims_.reserve(dims.size() + 1);
-  dims_.emplace_back(self_bdim.value());
-  for (auto dim : dims)
-  {
-    dims_.emplace_back(getPhysicalDim(self, true, dim));
-  }
-  return std::make_tuple(self.permute(dims_), self_bdim);
-}
+// std::tuple<Tensor, optional<int64_t>> permute_batching_rule(
+//     const Tensor &self, optional<int64_t> self_bdim, IntArrayRef dims)
+// {
+//   TORCH_INTERNAL_ASSERT(self_bdim.has_value());
+//   VmapDimVector dims_;
+//   dims_.reserve(dims.size() + 1);
+//   dims_.emplace_back(self_bdim.value());
+//   for (auto dim : dims)
+//   {
+//     dims_.emplace_back(getPhysicalDim(self, true, dim));
+//   }
+//   return std::make_tuple(self.permute(dims_), self_bdim);
+// }
 
 std::tuple<Tensor,optional<int64_t>> select_backward_batch_rule(
     const Tensor& grad_input, optional<int64_t> grad_input_bdim,
@@ -385,7 +385,6 @@ TORCH_LIBRARY_IMPL(aten, FT_BATCHED_KEY, m) {
   VMAP_SUPPORT("squeeze.dim", squeeze_dim_batch_rule);
   VMAP_SUPPORT("_reshape_alias", _reshape_alias_batch_rule);
   VMAP_SUPPORT("roll", roll_batch_rule);
-  VMAP_SUPPORT("permute", permute_batching_rule);
   VMAP_SUPPORT("diagonal", diagonal_batching_rule);
   VMAP_SUPPORT("diagonal_backward", diagonal_backward_batch_rule);
   VMAP_SUPPORT("select_backward", select_backward_batch_rule);
```

</details>

<details>

<summary>Test Logs</summary>

```
======================================================================
ERROR: test_permute_cpu (__main__.TestVmapBatchedGradientCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 1108, in wrapper
    method(*args, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2821, in test_permute
    self._batched_grad_test(op, (x,))
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2667, in _batched_grad_test
    self._vmap_test(vector_jacobian_product, batched_vectors,
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2649, in _vmap_test
    return _vmap_test(self, *args, **kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 1037, in _vmap_test
    result = vmap(op, in_dims, out_dims)(*inputs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/functorch-0.0.1a0+7491621-py3.9-linux-x86_64.egg/functorch/_src/vmap.py", line 278, in wrapped
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2665, in vector_jacobian_product
    return torch.autograd.grad(outputs, differentiable(args), vectors,
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/autograd/__init__.py", line 234, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: number of dims don't match in permute

======================================================================
ERROR: test_permute_cuda (__main__.TestVmapBatchedGradientCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 1108, in wrapper
    method(*args, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1397, in wrapper
    method(*args, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1397, in wrapper
    method(*args, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2821, in test_permute
    self._batched_grad_test(op, (x,))
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2667, in _batched_grad_test
    self._vmap_test(vector_jacobian_product, batched_vectors,
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2649, in _vmap_test
    return _vmap_test(self, *args, **kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 1037, in _vmap_test
    result = vmap(op, in_dims, out_dims)(*inputs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/functorch-0.0.1a0+7491621-py3.9-linux-x86_64.egg/functorch/_src/vmap.py", line 278, in wrapped
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2665, in vector_jacobian_product
    return torch.autograd.grad(outputs, differentiable(args), vectors,
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/autograd/__init__.py", line 234, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: number of dims don't match in permute

======================================================================
ERROR: test_op_has_batch_rule_permute_cpu_float32 (__main__.TestVmapOperatorsOpInfoCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 3086, in test_op_has_batch_rule
    check_vmap_fallback(self, test, op)
  File "/home/kshiteej/Pytorch/functorch/test/common_utils.py", line 155, in check_vmap_fallback
    thunk()
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 3084, in test
    for _ in get_fallback_and_vmap_exhaustive(op.op, arg_values, kwarg_values, compute_loop_out=False):
  File "/home/kshiteej/Pytorch/functorch/test/common_utils.py", line 82, in get_fallback_and_vmap_exhaustive
    batched_out = vmap(op, in_dims=in_dims, out_dims=out_dim)(*batched_args, **kwarg_values)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/functorch-0.0.1a0+7491621-py3.9-linux-x86_64.egg/functorch/_src/vmap.py", line 278, in wrapped
    batched_outputs = func(*batched_inputs, **kwargs)
RuntimeError: number of dims don't match in permute

======================================================================
ERROR: test_vmap_exhaustive_permute_cpu_float32 (__main__.TestVmapOperatorsOpInfoCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2987, in test_vmap_exhaustive
    raise e
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2981, in test_vmap_exhaustive
    for loop_out, batched_out in get_fallback_and_vmap_exhaustive(op.op, arg_values, kwarg_values):
  File "/home/kshiteej/Pytorch/functorch/test/common_utils.py", line 82, in get_fallback_and_vmap_exhaustive
    batched_out = vmap(op, in_dims=in_dims, out_dims=out_dim)(*batched_args, **kwarg_values)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/functorch-0.0.1a0+7491621-py3.9-linux-x86_64.egg/functorch/_src/vmap.py", line 278, in wrapped
    batched_outputs = func(*batched_inputs, **kwargs)
RuntimeError: number of dims don't match in permute

======================================================================
ERROR: test_op_has_batch_rule_permute_cuda_float32 (__main__.TestVmapOperatorsOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1397, in wrapper
    method(*args, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1397, in wrapper
    method(*args, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 3086, in test_op_has_batch_rule
    check_vmap_fallback(self, test, op)
  File "/home/kshiteej/Pytorch/functorch/test/common_utils.py", line 155, in check_vmap_fallback
    thunk()
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 3084, in test
    for _ in get_fallback_and_vmap_exhaustive(op.op, arg_values, kwarg_values, compute_loop_out=False):
  File "/home/kshiteej/Pytorch/functorch/test/common_utils.py", line 82, in get_fallback_and_vmap_exhaustive
    batched_out = vmap(op, in_dims=in_dims, out_dims=out_dim)(*batched_args, **kwarg_values)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/functorch-0.0.1a0+7491621-py3.9-linux-x86_64.egg/functorch/_src/vmap.py", line 278, in wrapped
    batched_outputs = func(*batched_inputs, **kwargs)
RuntimeError: number of dims don't match in permute

======================================================================
ERROR: test_vmap_exhaustive_permute_cuda_float32 (__main__.TestVmapOperatorsOpInfoCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1397, in wrapper
    method(*args, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_utils.py", line 1397, in wrapper
    method(*args, **kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2987, in test_vmap_exhaustive
    raise e
  File "/home/kshiteej/Pytorch/functorch/test/test_vmap.py", line 2981, in test_vmap_exhaustive
    for loop_out, batched_out in get_fallback_and_vmap_exhaustive(op.op, arg_values, kwarg_values):
  File "/home/kshiteej/Pytorch/functorch/test/common_utils.py", line 82, in get_fallback_and_vmap_exhaustive
    batched_out = vmap(op, in_dims=in_dims, out_dims=out_dim)(*batched_args, **kwarg_values)
  File "/home/kshiteej/.conda/envs/pytorch-cuda-dev/lib/python3.9/site-packages/functorch-0.0.1a0+7491621-py3.9-linux-x86_64.egg/functorch/_src/vmap.py", line 278, in wrapped
    batched_outputs = func(*batched_inputs, **kwargs)
RuntimeError: number of dims don't match in permute

----------------------------------------------------------------------
Ran 6 tests in 0.982s

FAILED (errors=6)
```

</details>

**Comment by Chillee** [comment]
Permute's batching rules doesn't follow the typical "reduction" template, which is basically "add one to each one of your dimensions". Permute also requires you to add an extra dimension to the front.

**Comment by Chillee** [comment]
By the way, don't feel a need to port over all of the "old" batching rules :P It's nice to have them ported over slowly, but they're also a good source for people to start writing batching rules :)

**Pull request merged**
