### PR TITLE
Added rot90 batch rule

### PR DESCRIPTION
**Pull request by vfdev-5**
Description:
- Added rot90 batch rule
- Enabled associated tests

Related to https://github.com/facebookresearch/functorch/issues/112

Note: tests seem not be reliable to output bdim.
Tests are passing even if batching rule outputs wrong bdim

### CODE REVIEW

**Comment by zou3519** [comment]
> Note: tests seem not be reliable to output bdim.
> Tests are passing even if batching rule outputs wrong bdim

Yeah our vmap tests don't test for non-zero bdim. We should fix that at some point...

**Comment by Chillee** [comment]
Does this work with `REDUCTION_BOXED`?

Specifically, `REDUCTION_BOXED_ARGS(rot90, 2)` (which specifies that the dim argument is at position 2).

**Comment by vfdev-5** [comment]
@Chillee I like this magical macro ! Yes, seems like tests are passing with REDUCTION_BOXED_ARGS and without writing any batching rule :)

**Comment by Chillee** [comment]
There's an xfail not passing - I suspect you need to also remove the test from the `has_batch_rule` OpInfo test.

**Comment by Chillee** [comment]
LGTM. Thanks!

**Pull request merged**
